#!/bin/bash

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

SEED=${1:-42}
TRAIN_METHOD=${2:-"dd"}
MODEL=${3:-"cnn"}
P=${4:-4}

DATASETS=("mnist" "fashionmnist" "cifar10" "cifar100")




TIMESTAMP=$(date +"%Y%m%d_%H%M%S")
RUNDIR="$PROJECT_ROOT/runs/experiment_only_${TRAIN_METHOD}_${TIMESTAMP}"

mkdir -p "$RUNDIR/logs"

echo "Submitting experiments for with model: ${MODEL} seed: $SEED train method: ${TRAIN_METHOD} and P: ${P}"
echo "Run directory: $RUNDIR"

for dataset in "${DATASETS[@]}"; do
    sbatch --job-name="single_train_method_${MODEL}" \
    --output="$RUNDIR/logs/train_${MODEL}_only${TRAIN_METHOD}_${dataset}_%j.out" \
    "$PROJECT_ROOT/scripts/train.slurm" \
    --dataset "$dataset" \
    --model "$MODEL" \
    --epochs 200 \
    --no-early-stopping \
    --train_method "$TRAIN_METHOD" \
    --dd_num_perturbations $P \
    --logdir "$RUNDIR" \
    --seed $SEED
done


echo "All jobs submitted!"
